/**
 * @file openlcb_can_drivers.h
 * @brief Hardware driver prototypes for CAN Drivers.
 *
 * @copyright
 *   Copyright (c) <YEAR>, <YOUR NAME OR COMPANY>
 *   <YOUR LICENSE TEXT HERE>
 *
 * Generated by Node Wizard — https://github.com/JimKueneman/OpenLcbCLib
 */

#ifndef __OPENLCB_CAN_DRIVERS__
#define __OPENLCB_CAN_DRIVERS__

#include <stdbool.h>

#include "drivers/canbus/can_types.h"


void can_driver_initialize(void);

bool can_driver_transmit(can_msg_t *can_msg);

bool can_driver_is_clear(void);

bool can_driver_is_connected(void);

bool can_driver_transmit_physical(can_msg_t *can_msg);


#endif /* __OPENLCB_CAN_DRIVERS__ */
