/*
 * This file is part of esp32_lever_frame.
 *
 * esp32_lever_frame is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * esp32_lever_frame is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with esp32_lever_frame.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file openlcb_can_drivers.h
 * @brief Hardware driver prototypes for CAN Drivers.
 *
 * @copyright
 *   Copyright (c) <YEAR>, <YOUR NAME OR COMPANY>
 *   <YOUR LICENSE TEXT HERE>
 *
 * Generated by Node Wizard — https://github.com/JimKueneman/OpenLcbCLib
 */

#ifndef __OPENLCB_CAN_DRIVERS__
#define __OPENLCB_CAN_DRIVERS__

#include <stdbool.h>

#include "drivers/canbus/can_types.h"


void can_driver_initialize(void);

bool can_driver_transmit(can_msg_t *can_msg);

bool can_driver_is_clear(void);

bool can_driver_is_connected(void);

bool can_driver_transmit_physical(can_msg_t *can_msg);


#endif /* __OPENLCB_CAN_DRIVERS__ */
