/*
 * This file is part of esp32_lever_frame.
 *
 * esp32_lever_frame is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * esp32_lever_frame is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with esp32_lever_frame.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file openlcb_drivers.h
 * @brief Hardware driver prototypes for OLCB/LCC Drivers.
 *
 * @copyright
 *   Copyright (c) <YEAR>, <YOUR NAME OR COMPANY>
 *   <YOUR LICENSE TEXT HERE>
 *
 * Generated by Node Wizard — https://github.com/JimKueneman/OpenLcbCLib
 */

#ifndef __OPENLCB_DRIVERS__
#define __OPENLCB_DRIVERS__

#include <stdint.h>

#include "openlcb/openlcb_types.h"
#include "openlcb_user_config.h"


void lcc_drivers_initialize(void);

void lcc_drivers_lock_shared_resources(void);

void lcc_drivers_unlock_shared_resources(void);

uint16_t lcc_drivers_config_mem_read(openlcb_node_t *openlcb_node, uint32_t address, uint16_t count, configuration_memory_buffer_t *buffer);

uint16_t lcc_drivers_config_mem_write(openlcb_node_t *openlcb_node, uint32_t address, uint16_t count, configuration_memory_buffer_t *buffer);

void lcc_drivers_reboot(openlcb_statemachine_info_t *statemachine_info, config_mem_operations_request_info_t *config_mem_operations_request_info);

void lcc_drivers_firmware_write(openlcb_statemachine_info_t *statemachine_info, config_mem_write_request_info_t *config_mem_write_request_info, write_result_t write_result);

void lcc_drivers_freeze(openlcb_statemachine_info_t *statemachine_info, config_mem_operations_request_info_t *config_mem_operations_request_info);

void lcc_drivers_unfreeze(openlcb_statemachine_info_t *statemachine_info, config_mem_operations_request_info_t *config_mem_operations_request_info);

node_config_memory_t* lcc_drivers_get_config(void);

#endif /* __OPENLCB_DRIVERS__ */
