/**
 * @file openlcb_tcpip_drivers.h
 * @brief Hardware driver prototypes for TCP/IP Drivers.
 *
 * @copyright
 *   Copyright (c) <YEAR>, <YOUR NAME OR COMPANY>
 *   <YOUR LICENSE TEXT HERE>
 *
 * Generated by Node Wizard — https://github.com/JimKueneman/OpenLcbCLib
 */

#ifndef __OPENLCB_TCP_DRIVERS__
#define __OPENLCB_TCP_DRIVERS__


void tcp_driver_initialize(void);



#endif /* __OPENLCB_TCP_DRIVERS__ */
